apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-fe
resources:
- namespace.yaml
- ../../base/fe


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-fe-ingress
images:
- name: scgskku/attendance-checker-fe-dev
  newTag: 42d4df6fad9adfcdfe4141ed38b6f80a819f6935-34033131286-1
