apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-fe
resources:
- namespace.yaml
- ../../base/fe


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-fe-ingress
images:
- name: scgskku/attendance-checker-fe-dev
  newTag: 78ee68fcdeb601461283f2ecd09b6c84439afed9-35355595956-1
