apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-fe
resources:
- namespace.yaml
- ../../base/fe


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-fe-ingress
images:
- name: scgskku/attendance-checker-fe-dev
  newTag: b82f3e4cad2385da425f679e446d8bd128c0cab6-34073167050-1
