apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-ingress
images:
- name: scgskku/attendance-checker-be-dev
  newTag: ef4cda5378d40a8153a4a8f23b6be693c62face3-33827823177-1
