apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-ingress
images:
- name: scgskku/attendance-checker-be-dev
  newTag: 5ae36d4a54d5fe255cdfa6d1d702fabe44c4f120-34595166947-1
