apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-ingress
images:
- name: scgskku/attendance-checker-be-dev
  newTag: 6b0f8f9473db7dcadcfc07e3e2710d5f31c4953d-33373486474-1
