apiVersion: v1
kind: Secret
metadata:
  name: attendance-checker-be-secret
  annotations:
    avp.kubernetes.io/path: kv/data/attendance-checker-be-dev-secret
type: Opaque
stringData:
  DATABASE_URL: <path:kv/data/attendance-checker-be-dev-secret#database_url>
  DATABASE_USERNAME: <path:kv/data/attendance-checker-be-dev-secret#database_username>
  DATABASE_PASSWORD: <path:kv/data/attendance-checker-be-dev-secret#database_password>
  GOOGLE_OAUTH_CLIENT_ID: <path:kv/data/attendance-checker-be-dev-secret#google_oauth_client_id>
  GOOGLE_OAUTH_CLIENT_SECRET: <path:kv/data/attendance-checker-be-dev-secret#google_oauth_client_secret>
  JWT_SECRET_KEY: <path:kv/data/attendance-checker-be-dev-secret#jwt_secret_key>
